language: bash

sudo: required

before_install:
  - openssl aes-256-cbc -K $encrypted_0900be937efe_key -iv $encrypted_0900be937efe_iv -in pages-deploy-key.enc -out pages-deploy-key -d

#install:
#  - sudo add-apt-repository -y ppa:avsm/ocaml42+opam12
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq ocaml opam
#  - export OPAMYES=1 && opam init && eval `opam config env`
#  #- opam install bisect ounit
#  - opam install js_of_ocaml tyxml deriving ppx_deriving reactiveData ocp-indent camomile

before_script:
  # Replace with the line that travis encrypt-file printed out
  #- openssl aes-256-cbc ...
  - chmod go-rwx pages-deploy-key
  - eval `ssh-agent -s`
  - ssh-add pages-deploy-key
  - git config user.name "Travis-CI"
  - git config user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from `git log -n 1 --format='commit %h - %s'`"
  
script: 
  - cd ./src
  - bash ./build.sh
  - git checkout -b master # Replace master with gh-pages if applicable
  - git add -f _site/ # Replace _site/ with the build's output directory
  - 'git commit -m "${COMMIT_MESSAGE}"'
  - git filter-branch -f --subdirectory-filter _site/ # Again, replace _site/
  # Obviously, replace with your repo's SSH URL and the appropriate branch
  - git push -f YOUR_REPOS_SSH_URL master:master
  
  branches:
  only:
    - source
